### ISSUE TITLE
demo 运行在UITableView中测测试问题

### ISSUE THREAD

**Issue by zeqinjie** [bestswifter/BSPanoramaView#3]
初次显示的cell 的全景图正常。但是后面的显示只是一张图片？

**Comment by bestswifter** [comment]
感谢指正，经过 debug 发现是注册时机错误，应该在 setImage 中注册而不是 init 中注册。因为 setImage 和 unloadImage 是可以多次调用的方法。马上修复

**Comment by zeqinjie** [comment]
谢谢你提供这个插件，我也刚刚修复这个问题。
- (void)setImageWithName:(NSString *)imageName {
    [[PanoramaManager sharedInstance] registerView:self];
   ........
}

**Comment by bestswifter** [comment]
已修复
